apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: healthcare-platform
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - identity-service.yaml
  - patient-service.yaml
  - doctor-service.yaml
  - appointment-service.yaml
  - emr-service.yaml
  - billing-service.yaml
  - notification-service.yaml
  - audit-service.yaml
  - analytics-service.yaml
  - graphql-gateway.yaml
  - frontend.yaml
