apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthcare-platform-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: healthcare-platform
  source:
    repoURL: https://github.com/ayia-hosni/healthcare-microservices-platform.git
    targetRevision: main
    path: infra/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: healthcare-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
